apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "trace-execve"
spec:
  kprobes:
  - call: "sys_execve"
    syscall: true
    args:
    - index: 0
      type: "string" # Le chemin du binaire (ex: /usr/bin/ls)
