"""
Anomaly Detector — Compare live snapshots against a learned baseline.

For every edge in a snapshot, checks whether the observed behavior
(spawn, file read/write, network connection) was seen during the
baseline phase. Unseen behaviors produce Alert objects.
"""

import uuid
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Dict, List

try:
    from .baseline import BaselineLearner
    from ingestion.constants import (
        NODE_PROCESS, NODE_FILE, NODE_SOCKET,
        REL_SPAWNS, REL_READS, REL_MODIFIES, REL_CONNECTS_TO,
    )
except ImportError:
    import sys as _sys, os as _os
    _sys.path.insert(0, _os.path.join(_os.path.dirname(__file__), ".."))
    _sys.path.insert(0, _os.path.join(_os.path.dirname(__file__), "..", "ingestion"))
    from baseline import BaselineLearner  # type: ignore[no-redef]
    from constants import (  # type: ignore[no-redef]
        NODE_PROCESS, NODE_FILE, NODE_SOCKET,
        REL_SPAWNS, REL_READS, REL_MODIFIES, REL_CONNECTS_TO,
    )

# File paths that always produce HIGH severity alerts
SENSITIVE_PATHS = (
    "/etc/passwd",
    "/etc/shadow",
    "/etc/sudoers",
    "/root/",
    "/.ssh/",
    "/etc/crontab",
    "/proc/",
)


def _is_sensitive(path: str) -> bool:
    return any(path == s or path.startswith(s) for s in SENSITIVE_PATHS)


# ─────────────────────────────────────────────────────────────────────────────
# Alert dataclass
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Alert:
    """A single anomaly detection alert."""
    id: str
    timestamp: str
    severity: str       # "HIGH" | "MEDIUM" | "LOW"
    alert_type: str     # See ALERT_* constants below
    process_comm: str
    description: str
    evidence: Dict[str, Any]


ALERT_UNKNOWN_PROCESS = "UNKNOWN_PROCESS"
ALERT_UNEXPECTED_SPAWN = "UNEXPECTED_SPAWN"
ALERT_UNEXPECTED_FILE_READ = "UNEXPECTED_FILE_READ"
ALERT_UNEXPECTED_FILE_WRITE = "UNEXPECTED_FILE_WRITE"
ALERT_UNEXPECTED_CONNECTION = "UNEXPECTED_CONNECTION"


def _new_alert(
    severity: str,
    alert_type: str,
    comm: str,
    description: str,
    evidence: Dict[str, Any],
) -> Alert:
    return Alert(
        id=uuid.uuid4().hex,
        timestamp=datetime.now().isoformat(),
        severity=severity,
        alert_type=alert_type,
        process_comm=comm,
        description=description,
        evidence=evidence,
    )


# ─────────────────────────────────────────────────────────────────────────────
# AnomalyDetector
# ─────────────────────────────────────────────────────────────────────────────

class AnomalyDetector:
    """
    Compares live graph snapshots against a BaselineLearner profile.

    Usage::

        detector = AnomalyDetector(learner)
        new_alerts = detector.detect(snapshot)
        all_alerts  = detector.alerts
    """

    def __init__(self, baseline: BaselineLearner) -> None:
        self._baseline = baseline
        self.alerts: List[Alert] = []

    def detect(self, snapshot: Dict[str, Any]) -> List[Alert]:
        """
        Analyse a snapshot and return alerts generated by this call.
        Alerts also accumulate in self.alerts.
        """
        profile = self._baseline.get_profile()
        behaviors = profile.get("behaviors", {})

        nodes = snapshot.get("nodes", [])
        edges = snapshot.get("edges", [])
        node_map: Dict[str, Dict[str, Any]] = {n["id"]: n for n in nodes}

        new_alerts: List[Alert] = []

        for edge in edges:
            src_id = edge.get("source")
            tgt_id = edge.get("target")
            relation = edge.get("relation")

            src_node = node_map.get(src_id)
            tgt_node = node_map.get(tgt_id)

            if src_node is None or tgt_node is None:
                continue
            if src_node.get("type") != NODE_PROCESS:
                continue

            comm: str = src_node.get("attributes", {}).get("comm", "unknown")
            evidence = {
                "edge": edge,
                "source_node": src_node,
                "target_node": tgt_node,
            }

            # Unknown process — no baseline data at all
            if comm not in behaviors:
                new_alerts.append(_new_alert(
                    severity="MEDIUM",
                    alert_type=ALERT_UNKNOWN_PROCESS,
                    comm=comm,
                    description="Process '{0}' was not seen during baseline.".format(comm),
                    evidence=evidence,
                ))
                continue

            comm_behavior = behaviors[comm]

            if relation == REL_SPAWNS:
                child_comm = tgt_node.get("attributes", {}).get("comm", "unknown")
                if child_comm not in comm_behavior.get("spawns", []):
                    new_alerts.append(_new_alert(
                        severity="HIGH",
                        alert_type=ALERT_UNEXPECTED_SPAWN,
                        comm=comm,
                        description=(
                            "'{0}' spawned '{1}', which was not observed during baseline.".format(
                                comm, child_comm
                            )
                        ),
                        evidence=evidence,
                    ))

            elif relation == REL_READS:
                path = tgt_node.get("attributes", {}).get("path", "")
                if path not in comm_behavior.get("reads", []):
                    severity = "HIGH" if _is_sensitive(path) else "MEDIUM"
                    new_alerts.append(_new_alert(
                        severity=severity,
                        alert_type=ALERT_UNEXPECTED_FILE_READ,
                        comm=comm,
                        description=(
                            "'{0}' read '{1}', which was not observed during baseline.".format(
                                comm, path
                            )
                        ),
                        evidence=evidence,
                    ))

            elif relation == REL_MODIFIES:
                path = tgt_node.get("attributes", {}).get("path", "")
                if path not in comm_behavior.get("writes", []):
                    severity = "HIGH" if _is_sensitive(path) else "MEDIUM"
                    new_alerts.append(_new_alert(
                        severity=severity,
                        alert_type=ALERT_UNEXPECTED_FILE_WRITE,
                        comm=comm,
                        description=(
                            "'{0}' wrote '{1}', which was not observed during baseline.".format(
                                comm, path
                            )
                        ),
                        evidence=evidence,
                    ))

            elif relation == REL_CONNECTS_TO:
                attrs = tgt_node.get("attributes", {})
                ip = attrs.get("ip", "")
                port = attrs.get("port", "")
                ip_port = "{0}:{1}".format(ip, port)
                if ip_port not in comm_behavior.get("connects", []):
                    new_alerts.append(_new_alert(
                        severity="HIGH",
                        alert_type=ALERT_UNEXPECTED_CONNECTION,
                        comm=comm,
                        description=(
                            "'{0}' connected to '{1}', which was not observed during baseline.".format(
                                comm, ip_port
                            )
                        ),
                        evidence=evidence,
                    ))

        self.alerts.extend(new_alerts)
        return new_alerts

    def clear_alerts(self) -> None:
        """Clear the accumulated alerts list."""
        self.alerts = []
